-- ============================================
-- ATOMIC CLIENT + PRIMARY CONTACT CREATION
-- Version: 003
-- Description: PostgreSQL function for atomic client+contact creation via RPC
-- ============================================

-- ============================================
-- 1. UNIQUE PARTIAL INDEX FOR PRIMARY CONTACT SAFETY
-- ============================================
-- This ensures only one primary contact per client at database level
-- Even if concurrent requests occur, the index prevents duplicates

CREATE UNIQUE INDEX IF NOT EXISTS idx_contacts_one_primary_per_client
  ON contacts(client_id)
  WHERE is_primary = TRUE AND deleted_at IS NULL;

-- ============================================
-- 2. ATOMIC CREATE CLIENT WITH CONTACT FUNCTION
-- ============================================
-- Creates a client and primary contact in a single atomic transaction
-- If either insert fails, entire transaction rolls back automatically

CREATE OR REPLACE FUNCTION create_client_with_contact(
  p_tenant_id UUID,
  p_user_id UUID,
  p_client_data JSONB,
  p_contact_data JSONB
)
RETURNS JSONB AS $$
DECLARE
  v_client clients;
  v_contact contacts;
BEGIN
  -- Validate required parameters
  IF p_tenant_id IS NULL THEN
    RAISE EXCEPTION 'tenant_id is required';
  END IF;

  IF p_user_id IS NULL THEN
    RAISE EXCEPTION 'user_id is required';
  END IF;

  IF p_client_data->>'name' IS NULL OR TRIM(p_client_data->>'name') = '' THEN
    RAISE EXCEPTION 'client name is required';
  END IF;

  IF p_contact_data->>'first_name' IS NULL OR TRIM(p_contact_data->>'first_name') = '' THEN
    RAISE EXCEPTION 'contact first_name is required';
  END IF;

  IF p_contact_data->>'last_name' IS NULL OR TRIM(p_contact_data->>'last_name') = '' THEN
    RAISE EXCEPTION 'contact last_name is required';
  END IF;

  -- Insert client
  -- Note: display_id is auto-generated by trigger (generate_clients_display_id)
  INSERT INTO clients (
    tenant_id,
    created_by,
    name,
    company_name,
    status,
    industry,
    location,
    overview,
    portal_enabled
  )
  VALUES (
    p_tenant_id,
    p_user_id,
    TRIM(p_client_data->>'name'),
    COALESCE(NULLIF(TRIM(p_client_data->>'company_name'), ''), TRIM(p_client_data->>'name')),
    COALESCE((p_client_data->>'status')::client_status, 'active'),
    p_client_data->>'industry',
    p_client_data->>'location',
    p_client_data->>'overview',
    COALESCE((p_client_data->>'portal_enabled')::boolean, false)
  )
  RETURNING * INTO v_client;

  -- Insert primary contact linked to new client
  -- Note: display_id is auto-generated by trigger (generate_contacts_display_id)
  INSERT INTO contacts (
    tenant_id,
    client_id,
    created_by,
    first_name,
    last_name,
    email,
    phone,
    role,
    relationship,
    is_primary
  )
  VALUES (
    p_tenant_id,
    v_client.id,
    p_user_id,
    TRIM(p_contact_data->>'first_name'),
    TRIM(p_contact_data->>'last_name'),
    NULLIF(TRIM(p_contact_data->>'email'), ''),
    NULLIF(TRIM(p_contact_data->>'phone'), ''),
    p_contact_data->>'role',
    p_contact_data->>'relationship',
    true  -- Always primary when creating with client
  )
  RETURNING * INTO v_contact;

  -- Return both records as JSONB object
  RETURN jsonb_build_object(
    'client', row_to_json(v_client),
    'contact', row_to_json(v_contact)
  );

EXCEPTION
  WHEN OTHERS THEN
    -- Re-raise with context for debugging
    -- The entire transaction is automatically rolled back
    RAISE EXCEPTION 'Failed to create client with contact: %', SQLERRM;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- ============================================
-- 3. GRANT EXECUTION PERMISSION
-- ============================================
-- Allow authenticated users to call this function via RPC

GRANT EXECUTE ON FUNCTION create_client_with_contact(UUID, UUID, JSONB, JSONB) TO authenticated;

-- ============================================
-- 4. VERIFICATION QUERY
-- ============================================
-- Run this after migration to verify function exists:
-- SELECT proname FROM pg_proc WHERE proname = 'create_client_with_contact';
